[package]
name = "generic_array"
version = "0.1.0"

[features]
more_lengths = []

[dependencies.std3]
path = "../../enderpearl/packages/std3"
version = "0.1.23"

[dependencies]
typenum = { version = "1.12", features = ["no_std"]}